arrowParens: always
bracketSpacing: true
endOfLine: crlf
bracketSameLine: true
printWidth: 80
proseWrap: preserve
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
jsxSingleQuote: true
