name: tyrion
description: Your AI-Enabled Personal Assistant

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  auto_route: ^7.4.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.1
  cloud_functions: ^4.3.1
  connectivity_plus: ^4.0.1
  design_language:
    path: ../packages/design_language
  dynamic_color: ^1.6.5
  firebase_analytics: ^10.4.1
  firebase_app_check: ^0.1.4+1
  firebase_app_installations: ^0.2.3+1
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_messaging: ^14.6.1
  firebase_performance: ^0.9.2+1
  firebase_remote_config: ^4.2.1
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.0.4
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.15
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  google_fonts: ^5.1.0
  # google_one_tap_sign_in: ^1.0.3
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  material_color_utilities: ^0.5.0
  moment_dart: ^0.18.1
  photo_view: ^0.14.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  video_player: ^2.6.1

dev_dependencies:
  analyzer: ">=5.10.0"
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  custom_lint: ^0.5.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/logo/android/
    - assets/images/logo/dark/
    - assets/images/logo/light/
    - assets/images/error/
    - assets/images/illustrations/
    - assets/videos/
    - assets/videos/launch_animations/
  # fonts:
  #   - family:
  #     fonts:
  #     - asset:
  #       style:
  #       weight:
  #     - asset:
  #       style:
  #       weight:
flutter_launcher_icons:
  image_path: "assets/images/logo/dark/logo.png"
  android: true
  min_sdk_android: 28
  image_path_android: "assets/images/logo/android/logo.png"
  adaptive_icon_background: "#0E141B"
  adaptive_icon_foreground: "assets/images/logo/android/logo-transparent.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo/dark/logo.png"
    background_color: "#0E141B"
    theme_color: "#00539B"

flutter_native_splash:
  color: "#F8F9FF"
  image: "assets/images/logo/android/background.png"
  color_dark: "#0E141B"
  android_12:
    image: assets/images/logo/android/logo-transparent.png
    color: "#F8F9FF"
    color_dark: "#0E141B"
